### PR TITLE
Added microauth-google to the fold.

### PR DESCRIPTION
**Pull request by rapzo**

### CODE REVIEW

**Comment by rapzo** [comment]
Although, i'm still waiting on microauth's owner's blessing on this one so, may be worth waiting on his saying.

**Comment by amio** [comment]
👍  If you got any progress on this, ping me then

**Comment by rapzo** [comment]
Maybe pinging him from here is wiser :-)
What do you say @dimapaloskin ?

**Comment by rapzo** [comment]
You know what, if you're willing, go for it. Meanwhile we will sort things
out. The module is published and it's all it matters. Soon, maybe today,
i'll patch it with per domain support (i use it under a google apps domain)
and so far so good.

**Comment by amio** [comment]
Sure, and thanks! ;-)

**Comment by dimapaloskin** [comment]
Hi, @rapzo. It was holidays for me, so sorry for the long answer :)

It would be cool to add your `microauth-google` in common list of `microauth` modules and migrate you repo into `microauth` organization. If you don't mind it, of course.

Another question, did you create some issue or pr in any repo from `microauth` organization? I can't find your request unfortunately :(

Anyway, good job and thank you :)

**Comment by rapzo** [comment]
@dimapaloskin I didn't, sorry (sent you an email though). I'll open there an issue.

**Pull request merged**
